SELECT '' AS 'INSTALLATION STARTING'\G

DROP DATABASE IF EXISTS guttman_202db_assign5;

CREATE DATABASE IF NOT EXISTS guttman_202db_assign5
CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

SHOW DATABASES\G

USE guttman_202db_assign5;
