DROP USER IF EXISTS 'admin_007'@'%';

SELECT 'ADDING USER admin_007' AS 'INSTALLATION PROGRESSING';

CREATE USER IF NOT EXISTS 'admin_007'@'%';
IDENTIFIED BY 'guttmanGrizzlies_2024'

WITH

-- SET RESOURCE LIMITS
MAX_QUERIES_PER_HOUR 20
MAX_UPDATES_PER HOUR 10
MAX_CONNECTIONS_PER HOUR 5
MAX_USER_CONNECTIONS 2

-- SET PASSWORD OPTIONS
FAILED-lOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_007'@'%';

SELECT user, show_db_priv, account_locked
FROM mysql.user;



SELECT user, show_db_priv, account_locked
FROM mysql.user;

FLUSH PRIVILEGES;
